# This workflow will build a golang project
# For more informatio
name: Integração Contínua

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.15'

    - name: Inicia banco
      run: docker compose  up -d postgres
      
    - name: Lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.5
        args: controllers/ database/ models/ routes/
 
- name: Test
  run: DB_HOST=${{ secrets.DB_HOST }} DB_PASSWORD=${{ secrects.DB_PASSWORD }} DB_NAME=${{ secrects.DB_NAME }} DB_PORT=${{ secrects.DB_PORT }} go test -v main_test.go

